import Head from "next/head";
import { useRouter } from "next/router";
import { FaFile } from "react-icons/fa";
export default function Home() {
  const history = useRouter();
  return (
    <div>
      <Head>
        <title>30 Day Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full font-serif  flex-col px-5">
        <div className="w-full capitalize text-[28px] h-[50px] flex justify-center items-center shadow-md">
          next 30 day Challenge
        </div>
        <div className="w-full h-auto py-5 flex flex-col items-center">
          <div
            onClick={() => history.push("/digitalLanding")}
            className="w-[600px] cursor-pointer border h-[120px] px-2 flex items-center justify-between"
          >
            <div className="w-[150px] ">
              <FaFile size={60} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
