import {
  BsAppIndicator,
  BsBank,
  BsCloudLightningFill,
  BsCurrencyYen,
  BsDashSquareDotted,
  BsFolder2Open,
  BsMoonStarsFill,
  BsScissors,
  BsTelephone,
} from "react-icons/bs";

export const careerdata = {
  clients: [
    {
      name: "dropbox",
      img: require("../../public/images/landing/dropbox.svg"),
    },
    {
      name: "slack",
      img: require("../../public/images/basics/slacklogo.png"),
    },
    {
      name: "upwork",
      img: require("../../public/images/basics/upworklogo.png"),
    },
    {
      name: "Google",
      img: require("../../public/images/basics/googleplay.png"),
    },
    {
      name: "Airbnb",
      img: require("../../public/images/landing/airbnb.svg"),
    },
    {
      name: "Spotyfiy",
      img: require("../../public/images/landing/spotify.svg"),
    },
    {
      name: "heroku",
      img: require("../../public/images/landing/heroku.svg"),
    },
    {
      name: "vimeo",
      img: require("../../public/images/landing/vimeo.svg"),
    },
    {
      name: "NetFlix",
      img: require("../../public/images/landing/netflix.svg"),
    },
  ],
  company: [
    {
      icon: require("../../public/images/landing/company1.png"),
      jobs: "112",
      title: "this is Company 1",
    },
    {
      icon: require("../../public/images/landing/company2.png"),
      jobs: "85",
      title: "Company Two Here",
    },
    {
      icon: require("../../public/images/landing/company3.png"),
      jobs: "56",
      title: "I am THREE",
    },
    {
      icon: require("../../public/images/landing/company4.png"),
      jobs: "87",
      title: "Fore Is Whore",
    },
    {
      icon: require("../../public/images/landing/company5.png"),
      jobs: "106",
      title: "Hi Five To You",
    },
    {
      icon: require("../../public/images/landing/company6.png"),
      jobs: "23",
      title: "Mr. Morelle and Sons",
    },
    {
      icon: require("../../public/images/landing/company7.png"),
      jobs: "98",
      title: "SEVEN going to HEVEN",
    },
    {
      icon: require("../../public/images/landing/company8.png"),
      jobs: "38",
      title: "Eight is Beting None",
    },
    {
      icon: require("../../public/images/landing/company9.png"),
      jobs: "113",
      title: "My Own Company",
    },
    {
      icon: require("../../public/images/landing/company10.png"),
      jobs: "85 ",
      title: "Cooing is BOOKING",
    },
  ],
  jobs: [
    {
      icon: require("../../public/images/landing/company1.png"),
      jobs: "112",
      jobtitle: "Data Science Engineer",
      location: "Chahabil,Kthmandu ,Nepal",
      c_name: "Hamro Software Comapany",
      date: "2022-05-03",
      experiences: "7 years",
      j_type: "freelance",
      salary: "negotiable",
      p_type: "Intern/Student",
    },
    {
      icon: require("../../public/images/landing/company2.png"),
      jobs: "85",
      jobtitle: "General Marketing Manager",
      location: "Putalisadak ,Kthmandu ,Nepal",
      c_name: "Hamro E-commerce",
      date: "2022-01-03",
      experiences: "8 years",
      j_type: "full tme",
      salary: "80,000",
      p_type: "Manager",
    },
    {
      icon: require("../../public/images/landing/company3.png"),
      jobs: "56",
      jobtitle: "Frontend Developer (React)",
      location: "Balkumari, lalitpur ,Nepal",
      c_name: "Ekbana Solutions",
      date: "2022-05-03",
      experiences: "7 years",
      j_type: "Fulltime",
      salary: "negotiable",
      p_type: "Sr. Dveloper",
    },
    {
      icon: require("../../public/images/landing/company4.png"),
      jobs: "87",
      jobtitle: "Data Science Engineer",
      location: "Chahabil,Kthmandu ,Nepal",
      c_name: "Hamro Software Comapany",
      date: "2022-05-03",
      experiences: "7 years",
      j_type: "freelance",
      salary: "negotiable",
      p_type: "Intern/Student",
    },
    {
      icon: require("../../public/images/landing/company5.png"),
      jobs: "106",
      jobtitle: "Data Science Engineer",
      location: "Chahabil,Kthmandu ,Nepal",
      c_name: "Hamro Software Comapany",
      date: "2022-05-03",
      experiences: "7 years",
      j_type: "freelance",
      salary: "negotiable",
      p_type: "Intern/Student",
    },
    {
      icon: require("../../public/images/landing/company6.png"),
      jobs: "23",
      jobtitle: "Data Science Engineer",
      location: "Chahabil,Kthmandu ,Nepal",
      c_name: "Hamro Software Comapany",
      date: "2022-05-03",
      experiences: "7 years",
      j_type: "freelance",
      salary: "negotiable",
      p_type: "Intern/Student",
    },
    {
      icon: require("../../public/images/landing/company7.png"),
      jobs: "98",
      jobtitle: "Data Science Engineer",
      location: "Chahabil,Kthmandu ,Nepal",
      c_name: "Hamro Software Comapany",
      date: "2022-05-03",
      experiences: "7 years",
      j_type: "freelance",
      salary: "negotiable",
      p_type: "Intern/Student",
    },
    {
      icon: require("../../public/images/landing/company8.png"),
      jobs: "38",
      jobtitle: "Software Engineer",
      location: "Chahabil,Kthmandu ,Nepal",
      c_name: "Nishan IT Comapany",
      date: "2022-06-03",
      experiences: "5 years",
      j_type: "Parttime",
      salary: "negotiable",
      p_type: "Technical Head",
    },
    {
      icon: require("../../public/images/landing/company9.png"),
      jobs: "113",
      jobtitle: "Data Science Engineer",
      location: "Chahabil,Kthmandu ,Nepal",
      c_name: "Hamro Software Comapany",
      date: "2022-05-03",
      experiences: "7 years",
      j_type: "freelance",
      salary: "negotiable",
      p_type: "Intern/Student",
    },
    {
      icon: require("../../public/images/landing/company10.png"),
      jobs: "85 ",
      jobtitle: "Data Science Engineer",
      location: "Chahabil,Kthmandu ,Nepal",
      c_name: "Hamro Software Comapany",
      date: "2022-05-03",
      experiences: "7 years",
      j_type: "freelance",
      salary: "negotiable",
      p_type: "Intern/Student",
    },
  ],
  category: [
    {
      name: "Accountaing",
      icon: <BsBank size={45} />,
    },
    {
      name: "Markiting",
      icon: <BsCloudLightningFill size={45} />,
    },
    {
      name: "Designing",
      icon: <BsMoonStarsFill size={45} />,
    },
    {
      name: "Banking",
      icon: <BsCurrencyYen size={45} />,
    },
    {
      name: "Customer Service",
      icon: <BsFolder2Open size={45} />,
    },
    {
      name: "Health Care",
      icon: <BsTelephone size={45} />,
    },
    {
      name: "Developmet",
      icon: <BsDashSquareDotted size={45} />,
    },
    {
      name: "Developmet",
      icon: <BsScissors size={45} />,
    },
  ],
  globle: [
    {
      jobs: "112",
      img: require("../../public/images/landing/travel1.jpg"),
      country: "London",
    },
    {
      jobs: "102",
      img: require("../../public/images/landing/comorus.jpg"),
      country: "Comorus",
    },
    {
      jobs: "125",
      img: require("../../public/images/landing/italy.jpg"),
      country: "Italy",
    },
    {
      jobs: "98",
      img: require("../../public/images/landing/kenya.jpg"),
      country: "Kenya",
    },
    {
      jobs: "108",
      img: require("../../public/images/landing/Agerbaingan.jpg"),
      country: "Agerbaigan",
    },
    {
      jobs: "108",
      img: require("../../public/images/landing/Netherland.jpg"),
      country: "Netherland",
    },
    {
      jobs: "118",
      img: require("../../public/images/landing/medascard.jpg"),
      country: "MedaScred",
    },
  ],
};
